#!/usr/bin/env bash
#
# docs.sh — build the docs/ GitHub Pages site locally and run the
# accessibility gate over it.
#
# `npm run docs:a11y` used to require a pre-built ./_site that nothing local
# could produce: this machine has no Jekyll setup, and macOS system Ruby is
# 2.6 and unwritable. CI builds the site with actions/jekyll-build-pages, so
# the gate was CI-only and every local failure had to be discovered by pushing.
#
# The build below runs the *same* toolchain that action does — the
# `github-pages` gem bundle, which pins Jekyll to 3.10 — inside a container, so
# nothing is installed on the host. Do NOT "simplify" this to the `jekyll/jekyll`
# image: that is plain Jekyll and does not carry `jekyll-relative-links`, the
# plugin that rewrites in-docs Markdown links to their built .html paths. The
# site then renders every in-docs link unrewritten, which looks like a bug in
# the docs and invites a "fix" that breaks the real build. See NOTES.md
# (2026-07-26) and docs/CI-CD.md.
#
# Usage: scripts/docs.sh <command>
#
#   build   render docs/ to tmp/_site with the github-pages bundle
#   a11y    build, then run tools/docs-a11y.mjs over the result
#
# First run pulls ruby:3.3-slim and compiles the bundle's native extensions
# (nokogiri, eventmachine), which needs build-essential and takes a few
# minutes. The gems land in tmp/docs-jekyll/vendor on the host, so every later
# run skips both steps. `npm run app:clean` does not touch them; delete
# tmp/docs-jekyll to force a rebuild.
#
# Everything is written under tmp/, which is gitignored, and never into docs/.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# Host-side scratch: the Gemfile, its lock, and the resolved gems. Persisting
# the bundle is what keeps the second run fast.
WORK_DIR=tmp/docs-jekyll
SITE_DIR=tmp/_site
RUBY_IMAGE=ruby:3.3-slim

# jekyll-github-metadata resolves this from `git remote` on a real checkout,
# but the container has no git, so it is passed explicitly. Same value the
# Pages build sees.
PAGES_REPO_NWO=kevinle3212/sensebridge

usage() {
	cat <<-'EOF'
		Usage: scripts/docs.sh <command>

		  build   render docs/ to tmp/_site with the github-pages bundle
		  a11y    build, then run tools/docs-a11y.mjs over the result
	EOF
}

# Exits with an actionable message rather than Docker's own, which reads as a
# network error when the daemon is simply not running.
require_docker() {
	if ! command -v docker >/dev/null 2>&1; then
		echo "docs.sh: docker not found — it is the only local path to the github-pages bundle (system Ruby is 2.6)." >&2
		exit 1
	fi
	if ! docker info >/dev/null 2>&1; then
		echo "docs.sh: the Docker daemon is not running — start Docker Desktop and retry." >&2
		exit 1
	fi
}

# Writes the Gemfile the container bundles from. Deliberately generated rather
# than committed: a tracked Gemfile at the repo root would make this look like
# a Ruby project and tempt tooling (and Dependabot) into managing it, when the
# only real dependency declaration for the site is GitHub's own Pages bundle.
write_gemfile() {
	mkdir -p "$WORK_DIR"
	cat >"$WORK_DIR/Gemfile" <<-'EOF'
		# Generated by scripts/docs.sh — not tracked, safe to delete.
		source "https://rubygems.org"
		gem "github-pages", group: :jekyll_plugins
	EOF
}

cmd_build() {
	require_docker
	write_gemfile
	# Runs as root so apt-get works. On Docker Desktop for macOS the bind mount
	# maps container root to the host user, so tmp/ does not come back
	# root-owned; on a Linux host it would, which is fine because CI never
	# takes this path — it uses actions/jekyll-build-pages directly.
	#
	# The working directory must be the one holding the Gemfile, and the
	# source/destination must therefore be absolute. Jekyll's
	# PluginManager.require_from_bundler is gated on `File.file?("Gemfile")` —
	# a *relative* probe — so running from /repo silently skips
	# `Bundler.require(:jekyll_plugins)` no matter what BUNDLE_GEMFILE says.
	# github-pages then never loads, never merges its default plugin set, and
	# jekyll-relative-links never runs: the build stays green and every in-docs
	# link renders unrewritten. That is the exact failure NOTES.md attributes
	# to the wrong image, reachable here with the right one.
	docker run --rm \
		-v "$REPO_ROOT:/repo" -w "/repo/$WORK_DIR" \
		-e BUNDLE_GEMFILE="/repo/$WORK_DIR/Gemfile" \
		-e BUNDLE_PATH="/repo/$WORK_DIR/vendor" \
		-e SITE_DEST="/repo/$SITE_DIR" \
		-e PAGES_REPO_NWO="$PAGES_REPO_NWO" \
		-e DEBIAN_FRONTEND=noninteractive \
		"$RUBY_IMAGE" sh -eu -c '
			if ! bundle check >/dev/null 2>&1; then
				apt-get update -qq
				apt-get install -y -qq --no-install-recommends build-essential >/dev/null
				bundle install --quiet
			fi
			bundle exec jekyll build --source /repo/docs --destination "$SITE_DEST"
		'
	echo "docs.sh: built $SITE_DIR"
}

# Installs pa11y and puppeteer on demand. They stay out of package.json for the
# same reason ci.yml installs them with --no-save: a ~350MB Chrome download
# must not tax every other task that runs `npm install` at this root.
#
# The puppeteer version is pinned to whatever website/ already has, so this
# reuses that Chrome from ~/.cache/puppeteer instead of downloading a second
# copy. That also narrows a known trap: under Node 26, Puppeteer's own
# extraction can truncate a browser download while still exiting 0 (see
# website/README.md for the `unzip` repair).
#
# chrome-headless-shell is skipped outright. pa11y calls `puppeteer.launch()`
# with the default headless mode, which runs the *full* Chrome binary — the
# shell build is only used for `headless: "shell"`, so downloading it costs
# ~150MB that this gate never opens.
ensure_runner_deps() {
	if node -e 'require.resolve("pa11y"); require.resolve("puppeteer")' 2>/dev/null; then
		return
	fi
	local pinned
	pinned="$(node -p "require('./website/node_modules/puppeteer/package.json').version" 2>/dev/null || true)"
	echo "docs.sh: installing pa11y and puppeteer (not saved to package.json)…"
	PUPPETEER_SKIP_CHROME_HEADLESS_SHELL_DOWNLOAD=true \
		npm install --no-save pa11y "puppeteer${pinned:+@$pinned}"
}

cmd_a11y() {
	cmd_build
	ensure_runner_deps
	node tools/docs-a11y.mjs "$SITE_DIR"
}

case "${1:-}" in
	build) cmd_build ;;
	a11y) cmd_a11y ;;
	*)
		usage >&2
		exit 1
		;;
esac
