#!/usr/bin/swift
import CreateML
import Foundation

// Trains the bundled sound classifier and writes the model **plus a metrics
// report** next to it.
//
// The report is not decoration. The 2026-08-05 safety-framing verdict
// (audits/safety-framing/20260805-205701-…-alpha-acceptability-verdict.md)
// found that no per-class measurement of `fire_alarm` or `siren` existed
// anywhere in this repository: the script printed one dataset-wide aggregate
// over all seven classes to stdout, and that number was then quoted as if it
// described those two classes. It also found the aggregate is not stable —
// three runs on unchanged data scored 7.2%, 11.7%, and ~43%, because Create ML
// holds out 8 of 78 files across 7 classes, so a class's recall is estimated
// from roughly one clip.
//
// Writing precision/recall and the confusion matrix to a file beside the
// `.mlmodel` means the shipped artifact carries its own provenance instead of
// losing it to a terminal scrollback, and makes the instability visible rather
// than inferable. It does not fix the instability — that needs a fixed held-out
// set, which is recommendation #2 in the same report and a separate change.

let arguments = CommandLine.arguments
guard arguments.count == 3 else {
    print("Usage: train.swift <training-data-path> <output-mlmodel-path>")
    exit(1)
}
let trainingDataURL = URL(fileURLWithPath: arguments[1])
let outputURL = URL(fileURLWithPath: arguments[2])

let dataSource = MLSoundClassifier.DataSource.labeledDirectories(at: trainingDataURL)
let classifier = try MLSoundClassifier(trainingData: dataSource)

let metadata = MLModelMetadata(
    author: "SenseBridge",
    shortDescription: "On-device sound classifier for high-value alerts, trained on individually license-verified clips.",
    license: "See CREDITS.md and models/sound-classifier/freesound-training-data/MANIFEST.csv for full per-clip attribution."
)
try classifier.write(to: outputURL, metadata: metadata)

// `classificationError`, not accuracy. The previous version of this script
// printed the error under the label "accuracy", so a 0.215 error read as 21.5%
// accuracy to anyone skimming — the inverse of the truth, on a safety-adjacent
// model.
let trainingError = classifier.trainingMetrics.classificationError
let validationError = classifier.validationMetrics.classificationError

let report = """
# Sound classifier metrics

Generated by `models/sound-classifier/train.swift`. Regenerated on every train;
commit it alongside the `.mlmodel` so the artifact carries its own provenance.

- Training data: `\(trainingDataURL.path)`
- Model: `\(outputURL.lastPathComponent)`

## Aggregate

Dataset-wide across **all** classes, not per class. Do not quote either figure
as the accuracy of any single class.

| Metric | Value |
| --- | --- |
| Training classification error | \(trainingError) |
| Validation classification error | \(validationError) |

**This aggregate is unstable.** Create ML resamples a small random holdout, so
repeated runs on identical data vary widely (7.2%, 11.7%, and ~43% were measured
on 2026-08-05). Treat a single run's figure as one draw, never as a property of
the model, and never as an alpha gate on its own.

## Per-class validation precision and recall

\(classifier.validationMetrics.precisionRecall)

## Validation confusion matrix

\(classifier.validationMetrics.confusion)
"""

let reportURL = outputURL.deletingLastPathComponent()
    .appendingPathComponent("\(outputURL.deletingPathExtension().lastPathComponent)-metrics.md")
try report.write(to: reportURL, atomically: true, encoding: .utf8)

print("Trained model written to \(outputURL.path)")
print("Metrics report written to \(reportURL.path)")
print("Training classification error: \(trainingError)")
print("Validation classification error: \(validationError)")
print("Per-class figures are in the report — the aggregate above describes all classes together.")
